template: "hello %s!"
database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: postgres
  url: jdbc:postgresql://192.168.99.100:5432/postgres
  validationQuery: "/* MyService Health Check */ SELECT 1"